project:
  output-dir: _output

toc: true
number-sections: true
bibliography: notebooks/references.bib
  
format:
  html:
    html-math-method: katex
  pdf:
    documentclass: report
    margin-left: 30mm
    margin-right: 30mm
  
#taken from quarto project basics https://quarto.org/docs/projects/quarto-projects.html#project-metadata