services:
  analysis:
    image: jacoblum22/dsci-310-group-03@sha256:b88aaf638ca3379d2478c4c27d60a68d6cd50db9e732d1bba63a79c2da124f2d
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    working_dir: /home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''
    
