services:
  analysis:
    image: jacoblum22/dsci-310-group-03@sha256:e69bf54a3686be8cc48fc2544b1f8d6418495aaca68d99dbb88772fdbbd9ec61
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    working_dir: /home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''
    
