<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Arnav Gupta">
<meta name="author" content="Ashley Chan">
<meta name="author" content="Jacob Andersen-Lum">
<meta name="author" content="Nathan Shack">

<title>Predicting Wine Quality from Physicochemical Properties</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="wine_quality_prediction_files/libs/clipboard/clipboard.min.js"></script>
<script src="wine_quality_prediction_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="wine_quality_prediction_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="wine_quality_prediction_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="wine_quality_prediction_files/libs/quarto-html/popper.min.js"></script>
<script src="wine_quality_prediction_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="wine_quality_prediction_files/libs/quarto-html/anchor.min.js"></script>
<link href="wine_quality_prediction_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="wine_quality_prediction_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="wine_quality_prediction_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="wine_quality_prediction_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="wine_quality_prediction_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Predicting Wine Quality from Physicochemical Properties</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Arnav Gupta </p>
             <p>Ashley Chan </p>
             <p>Jacob Andersen-Lum </p>
             <p>Nathan Shack </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>This project investigates whether the quality of wine can be predicted from its physicochemical properties using a K-Nearest Neighbors (KNN) regression approach. We use the Wine Quality dataset from the UCI Machine Learning Repository <span class="citation" data-cites="CORTEZ2009547">(<a href="#ref-CORTEZ2009547" role="doc-biblioref">Cortez et al. 2009</a>)</span>, which contains physicochemical measurements and sensory quality ratings for Portuguese “Vinho Verde” wine samples. We train a KNN regression model to predict wine quality scores from features such as alcohol content, acidity, pH, and residual sugar.</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Wine quality evaluation has historically been a very subjective process that mainly relies on human tasters’ sensory skills to evaluate intricate flavor profiles, aromas, and textures. Although human evaluation is crucial, it can be costly, time-consuming, and biased. Researchers and winemakers are increasingly using objective measurements - the physicochemical characteristics of wine - to supplement sensory testing. These properties refer to the quantifiable chemical and physical attributes of the liquid, such as its alcohol content, acidity levels, pH, and residual sugar. We can investigate the connection between a wine’s chemical composition and its perceived human taste by examining such objective metrics.</p>
<p>This leads us to our primary predictive question: <strong>Can we predict the quality score of a wine based on its physicochemical properties?</strong></p>
<p>To answer this question, we utilize the Wine Quality dataset from the UCI Machine Learning Repository (Cortez et al., 2009; Dua &amp; Graff, 2019). The sensory and chemical information in this dataset comes from samples of “Vinho Verde,” a well-known wine made in Portugal’s Minho region. Each wine sample in the dataset includes 11 continuous physicochemical characteristics, alongside a target variable: a sensory quality rating assessed by human experts on an integer scale from 3 to 10. We merge the red and white wine datasets into a single, comprehensive dataset for the purposes of this analysis.</p>
<p>To model the relationship between the chemical inputs and the quality output, we will employ a K-Nearest Neighbors (KNN) regression approach <span class="citation" data-cites="hastie_tibshirani_friedman_2009">(<a href="#ref-hastie_tibshirani_friedman_2009" role="doc-biblioref">Hastie, Tibshirani, and Friedman 2009</a>)</span>. By standardizing the chemical features and using cross-validation, our model will attempt to predict a wine’s quality score based on the ratings of wines with the most similar chemical profiles.</p>
</section>
<section id="methods-results" class="level2">
<h2 class="anchored" data-anchor-id="methods-results">Methods &amp; Results</h2>
<section id="data-loading" class="level3">
<h3 class="anchored" data-anchor-id="data-loading">Data Loading</h3>
<p>We load the Wine Quality dataset directly from the UCI Machine Learning Repository using the <code>ucimlrepo</code> package. This ensures the data is reproducibly downloaded from the original source.</p>
<div id="a7323121" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">fixed_acidity</th>
<th data-quarto-table-cell-role="th">volatile_acidity</th>
<th data-quarto-table-cell-role="th">citric_acid</th>
<th data-quarto-table-cell-role="th">residual_sugar</th>
<th data-quarto-table-cell-role="th">chlorides</th>
<th data-quarto-table-cell-role="th">free_sulfur_dioxide</th>
<th data-quarto-table-cell-role="th">total_sulfur_dioxide</th>
<th data-quarto-table-cell-role="th">density</th>
<th data-quarto-table-cell-role="th">pH</th>
<th data-quarto-table-cell-role="th">sulphates</th>
<th data-quarto-table-cell-role="th">alcohol</th>
<th data-quarto-table-cell-role="th">quality</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>7.4</td>
<td>0.70</td>
<td>0.00</td>
<td>1.9</td>
<td>0.076</td>
<td>11.0</td>
<td>34.0</td>
<td>0.9978</td>
<td>3.51</td>
<td>0.56</td>
<td>9.4</td>
<td>5</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>7.8</td>
<td>0.88</td>
<td>0.00</td>
<td>2.6</td>
<td>0.098</td>
<td>25.0</td>
<td>67.0</td>
<td>0.9968</td>
<td>3.20</td>
<td>0.68</td>
<td>9.8</td>
<td>5</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>7.8</td>
<td>0.76</td>
<td>0.04</td>
<td>2.3</td>
<td>0.092</td>
<td>15.0</td>
<td>54.0</td>
<td>0.9970</td>
<td>3.26</td>
<td>0.65</td>
<td>9.8</td>
<td>5</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>11.2</td>
<td>0.28</td>
<td>0.56</td>
<td>1.9</td>
<td>0.075</td>
<td>17.0</td>
<td>60.0</td>
<td>0.9980</td>
<td>3.16</td>
<td>0.58</td>
<td>9.8</td>
<td>6</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>7.4</td>
<td>0.70</td>
<td>0.00</td>
<td>1.9</td>
<td>0.076</td>
<td>11.0</td>
<td>34.0</td>
<td>0.9978</td>
<td>3.51</td>
<td>0.56</td>
<td>9.4</td>
<td>5</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="79832da6" class="cell" data-execution_count="3">
<div class="cell-output cell-output-stdout">
<pre><code>Dataset shape: (6497, 12)

Column types:
fixed_acidity           float64
volatile_acidity        float64
citric_acid             float64
residual_sugar          float64
chlorides               float64
free_sulfur_dioxide     float64
total_sulfur_dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

Missing values:
fixed_acidity           0
volatile_acidity        0
citric_acid             0
residual_sugar          0
chlorides               0
free_sulfur_dioxide     0
total_sulfur_dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

Quality score distribution:
quality
3      30
4     216
5    2138
6    2836
7    1079
8     193
9       5
Name: count, dtype: int64</code></pre>
</div>
</div>
</section>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<div class="cell" data-execution_count="4">
<div id="tbl-variables" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="4">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-variables-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Wine Variables
</figcaption>
<div aria-describedby="tbl-variables-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="4">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 16%">
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 59%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Role</th>
<th style="text-align: left;">Type</th>
<th style="text-align: left;">Missing</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">fixed_acidity</td>
<td style="text-align: left;">Feature</td>
<td style="text-align: left;">Continuous</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Amount of fixed (non-volatile) acids; mainly tartaric acid (g/dm³)</td>
</tr>
<tr class="even">
<td style="text-align: left;">volatile_acidity</td>
<td style="text-align: left;">Feature</td>
<td style="text-align: left;">Continuous</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Amount of acetic acid; high levels lead to a vinegar taste (g/dm³)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">citric_acid</td>
<td style="text-align: left;">Feature</td>
<td style="text-align: left;">Continuous</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Small quantities add freshness and flavour (g/dm³)</td>
</tr>
<tr class="even">
<td style="text-align: left;">residual_sugar</td>
<td style="text-align: left;">Feature</td>
<td style="text-align: left;">Continuous</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Sugar remaining after fermentation stops (g/dm³)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">chlorides</td>
<td style="text-align: left;">Feature</td>
<td style="text-align: left;">Continuous</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Amount of salt in the wine (g/dm³)</td>
</tr>
<tr class="even">
<td style="text-align: left;">free_sulfur_dioxide</td>
<td style="text-align: left;">Feature</td>
<td style="text-align: left;">Continuous</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Free form of SO₂; prevents microbial growth and oxidation (mg/dm³)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">total_sulfur_dioxide</td>
<td style="text-align: left;">Feature</td>
<td style="text-align: left;">Continuous</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Total SO₂ (free + bound); detectable above 50 mg/L (mg/dm³)</td>
</tr>
<tr class="even">
<td style="text-align: left;">density</td>
<td style="text-align: left;">Feature</td>
<td style="text-align: left;">Continuous</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Density of the wine, close to water depending on alcohol/sugar content (g/cm³)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pH</td>
<td style="text-align: left;">Feature</td>
<td style="text-align: left;">Continuous</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Acidity on a 0–14 scale; most wines fall between 3–4</td>
</tr>
<tr class="even">
<td style="text-align: left;">sulphates</td>
<td style="text-align: left;">Feature</td>
<td style="text-align: left;">Continuous</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Additive contributing to SO₂ levels; acts as antimicrobial agent (g/dm³)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">alcohol</td>
<td style="text-align: left;">Feature</td>
<td style="text-align: left;">Continuous</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Percentage of alcohol by volume (% vol)</td>
</tr>
<tr class="even">
<td style="text-align: left;">quality</td>
<td style="text-align: left;">Target</td>
<td style="text-align: left;">Ordinal</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Wine quality score assigned by sensory evaluation (integer, 0–10)</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The Wine Quality dataset comes relatively clean with no missing values. We combine the features and target into a single DataFrame and save the processed data for downstream analysis. The dataset has 6497 rows and 12 columns.</p>
<p><a href="#tbl-variables" class="quarto-xref">Table&nbsp;1</a> contains the physicochemical properties and sensory quality ratings of red and white wines found within the dataset. Each row represents a single wine sample, with 11 continuous features describing chemical characteristics such as fixed acidity, volatile acidity, citric acid, residual sugar, chlorides, sulfur dioxide, density, pH level, sulphates, and alchohol levels. The target variable, <code>quality</code>, is an ordinal score from 3-9 assigned by human tasters based on sensory evaluation.</p>
</section>
<section id="exploratory-data-analysis" class="level3">
<h3 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory Data Analysis</h3>
<section id="summary-statistics" class="level4">
<h4 class="anchored" data-anchor-id="summary-statistics">Summary Statistics</h4>
<div class="cell" data-execution_count="6">
<div id="tbl-wine-describe" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="6">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-wine-describe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Description of the variables in the wine dataset
</figcaption>
<div aria-describedby="tbl-wine-describe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="6">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">fixed_acidity</th>
<th style="text-align: right;">volatile_acidity</th>
<th style="text-align: right;">citric_acid</th>
<th style="text-align: right;">residual_sugar</th>
<th style="text-align: right;">chlorides</th>
<th style="text-align: right;">free_sulfur_dioxide</th>
<th style="text-align: right;">total_sulfur_dioxide</th>
<th style="text-align: right;">density</th>
<th style="text-align: right;">pH</th>
<th style="text-align: right;">sulphates</th>
<th style="text-align: right;">alcohol</th>
<th style="text-align: right;">quality</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">6497</td>
<td style="text-align: right;">6497</td>
<td style="text-align: right;">6497</td>
<td style="text-align: right;">6497</td>
<td style="text-align: right;">6497</td>
<td style="text-align: right;">6497</td>
<td style="text-align: right;">6497</td>
<td style="text-align: right;">6497</td>
<td style="text-align: right;">6497</td>
<td style="text-align: right;">6497</td>
<td style="text-align: right;">6497</td>
<td style="text-align: right;">6497</td>
</tr>
<tr class="even">
<td style="text-align: right;">7.21531</td>
<td style="text-align: right;">0.339666</td>
<td style="text-align: right;">0.318633</td>
<td style="text-align: right;">5.44324</td>
<td style="text-align: right;">0.0560339</td>
<td style="text-align: right;">30.5253</td>
<td style="text-align: right;">115.745</td>
<td style="text-align: right;">0.994697</td>
<td style="text-align: right;">3.2185</td>
<td style="text-align: right;">0.531268</td>
<td style="text-align: right;">10.4918</td>
<td style="text-align: right;">5.81838</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1.29643</td>
<td style="text-align: right;">0.164636</td>
<td style="text-align: right;">0.145318</td>
<td style="text-align: right;">4.7578</td>
<td style="text-align: right;">0.0350336</td>
<td style="text-align: right;">17.7494</td>
<td style="text-align: right;">56.5219</td>
<td style="text-align: right;">0.00299867</td>
<td style="text-align: right;">0.160787</td>
<td style="text-align: right;">0.148806</td>
<td style="text-align: right;">1.19271</td>
<td style="text-align: right;">0.873255</td>
</tr>
<tr class="even">
<td style="text-align: right;">3.8</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.6</td>
<td style="text-align: right;">0.009</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.98711</td>
<td style="text-align: right;">2.72</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6.4</td>
<td style="text-align: right;">0.23</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">1.8</td>
<td style="text-align: right;">0.038</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">77</td>
<td style="text-align: right;">0.99234</td>
<td style="text-align: right;">3.11</td>
<td style="text-align: right;">0.43</td>
<td style="text-align: right;">9.5</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.29</td>
<td style="text-align: right;">0.31</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.047</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">118</td>
<td style="text-align: right;">0.99489</td>
<td style="text-align: right;">3.21</td>
<td style="text-align: right;">0.51</td>
<td style="text-align: right;">10.3</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7.7</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">0.39</td>
<td style="text-align: right;">8.1</td>
<td style="text-align: right;">0.065</td>
<td style="text-align: right;">41</td>
<td style="text-align: right;">156</td>
<td style="text-align: right;">0.99699</td>
<td style="text-align: right;">3.32</td>
<td style="text-align: right;">0.6</td>
<td style="text-align: right;">11.3</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td style="text-align: right;">15.9</td>
<td style="text-align: right;">1.58</td>
<td style="text-align: right;">1.66</td>
<td style="text-align: right;">65.8</td>
<td style="text-align: right;">0.611</td>
<td style="text-align: right;">289</td>
<td style="text-align: right;">440</td>
<td style="text-align: right;">1.03898</td>
<td style="text-align: right;">4.01</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">14.9</td>
<td style="text-align: right;">9</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Above, <a href="#tbl-wine-describe" class="quarto-xref">Table&nbsp;2</a> below provides summary statistics for all numeric features in the dataset, including count, mean, standard deviation, minimum, maximum, and quartiles (25%, 50%, 75%) for each variable. This provides a quick glance at the general spread and range of the features in the dataset.</p>
<p>Most wines have moderate acidity, low volatile acidity, and around 9-11% alcohol, with a median quality of 6.</p>
<section id="distribution-of-wine-quality" class="level5">
<h5 class="anchored" data-anchor-id="distribution-of-wine-quality">Distribution of Wine Quality</h5>
<div id="cell-fig-wine-quality-distribution-bar" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div id="fig-wine-quality-distribution-bar" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-wine-quality-distribution-bar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="wine_quality_prediction_files/figure-html/fig-wine-quality-distribution-bar-output-1.png" width="602" height="429" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-wine-quality-distribution-bar-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Distribution of Wine Quality Scores
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-wine-quality-distribution-bar" class="quarto-xref">Figure&nbsp;1</a> is a distrubution of wine quality scores as a bar chart, showing how many wines in the dataset fall into each quality category.</p>
<p>The target variable, Wine Quality, is approximately normally distributed, with a mean of 5.82 and a mode of 6. Most wines fall in the mid-quality range of 4.95 - 6.69, indicating that extremely low or high quality wines are less common.</p>
</section>
<section id="correlation-heatmap-of-wine-features" class="level5">
<h5 class="anchored" data-anchor-id="correlation-heatmap-of-wine-features">Correlation Heatmap of Wine Features</h5>
<p>This correlation heatmap visualizes the correlation between all features within the wine dataset.</p>
<p>We can see that the features <code>density</code> and <code>alcohol</code> have a strong inverse relationship (-0.69). <code>total_sulfur_dioxide</code> is strongly correlated with <code>free_sulfur_dioxide</code> (+0.72), which makes sense since the free sulfur dioxide is included in the total amount. <code>residual_sugar</code> shows moderate correlations with <code>total_sulfur_dioxide</code>, <code>free_sulfur_dioxide</code>, and <code>density</code>. The target variable <code>quality</code> has its strongest relationships with <code>alcohol</code> (+0.44) and <code>volatile_acidity</code> (-0.27), suggesting that these features may be particularly important for predicting wine quality.</p>
<div id="7bd12d28" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="wine_quality_prediction_files/figure-html/cell-9-output-1.png" width="731" height="695" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="correlation-of-alcohol-and-quality" class="level5">
<h5 class="anchored" data-anchor-id="correlation-of-alcohol-and-quality">Correlation of Alcohol and Quality</h5>
<p>The box plots show the distribution of alcohol content for each wine score.</p>
<p>We can observe a slight positive correlation between Wine Quality and alcohol content. Higher-quality wines (7, 8, 9) generally have higher mean alcohol levels. Interestingly, the mean alcohol content decreases slightly for lower-quality wines (3–5) and then begins to increase from quality 6 onward.</p>
<div id="eff7d6b2" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="wine_quality_prediction_files/figure-html/cell-10-output-1.png" width="659" height="449" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="regression-analysis" class="level3">
<h3 class="anchored" data-anchor-id="regression-analysis">Regression Analysis</h3>
<p>We will perform K-Nearest Neighbors (KNN) regression to predict wine quality based on the chemical features of the wines. The dataset will be split into a training set and a 30% test set, and a pipeline will be used to preprocess and scale all features using scikit-learn (Pedregosa et al., 2011). We will then conduct a grid search to select the optimal number of neighbors (K) and evaluate the model’s performance on the test set to assess its predictive accuracy.</p>
<section id="splitting-the-data-into-training-testing-sets" class="level4">
<h4 class="anchored" data-anchor-id="splitting-the-data-into-training-testing-sets">Splitting the Data into Training &amp; Testing Sets</h4>
<p>The dataset will be split into 70% training data and 30% test data</p>
<div id="ce6ef16a" class="cell" data-execution_count="10">
<div class="cell-output cell-output-stdout">
<pre><code>X_train size: (4547, 11)
X_test size: (1950, 11)</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="10">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">fixed_acidity</th>
<th data-quarto-table-cell-role="th">volatile_acidity</th>
<th data-quarto-table-cell-role="th">citric_acid</th>
<th data-quarto-table-cell-role="th">residual_sugar</th>
<th data-quarto-table-cell-role="th">chlorides</th>
<th data-quarto-table-cell-role="th">free_sulfur_dioxide</th>
<th data-quarto-table-cell-role="th">total_sulfur_dioxide</th>
<th data-quarto-table-cell-role="th">density</th>
<th data-quarto-table-cell-role="th">pH</th>
<th data-quarto-table-cell-role="th">sulphates</th>
<th data-quarto-table-cell-role="th">alcohol</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">2457</th>
<td>6.7</td>
<td>0.22</td>
<td>0.39</td>
<td>10.2</td>
<td>0.038</td>
<td>60.0</td>
<td>149.0</td>
<td>0.99725</td>
<td>3.17</td>
<td>0.54</td>
<td>10.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">524</th>
<td>9.2</td>
<td>0.43</td>
<td>0.49</td>
<td>2.4</td>
<td>0.086</td>
<td>23.0</td>
<td>116.0</td>
<td>0.99760</td>
<td>3.23</td>
<td>0.64</td>
<td>9.5</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4551</th>
<td>6.1</td>
<td>0.27</td>
<td>0.25</td>
<td>1.8</td>
<td>0.041</td>
<td>9.0</td>
<td>109.0</td>
<td>0.99290</td>
<td>3.08</td>
<td>0.54</td>
<td>9.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5954</th>
<td>6.4</td>
<td>0.31</td>
<td>0.28</td>
<td>2.5</td>
<td>0.039</td>
<td>34.0</td>
<td>137.0</td>
<td>0.98946</td>
<td>3.22</td>
<td>0.38</td>
<td>12.7</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">3759</th>
<td>6.0</td>
<td>0.33</td>
<td>0.38</td>
<td>9.7</td>
<td>0.040</td>
<td>29.0</td>
<td>124.0</td>
<td>0.99540</td>
<td>3.47</td>
<td>0.48</td>
<td>11.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="creating-a-pipeline" class="level4">
<h4 class="anchored" data-anchor-id="creating-a-pipeline">Creating a Pipeline</h4>
<p>Since all the features in our dataset are numeric but may have different ranges and units, we will standardize them so that each feature contributes equally to the distance calculations in the K-Nearest Neighbors model. This scaling step ensures that features with larger numerical values do not dominate the model and allows the algorithm to measure similarity between samples more accurately.</p>
<div id="992d7c83" class="cell" data-execution_count="11">
<div class="cell-output cell-output-display" data-execution_count="11">
<style>#sk-container-id-1 {
  /* Definition of color scheme common for light and dark mode */
  --sklearn-color-text: #000;
  --sklearn-color-text-muted: #666;
  --sklearn-color-line: gray;
  /* Definition of color scheme for unfitted estimators */
  --sklearn-color-unfitted-level-0: #fff5e6;
  --sklearn-color-unfitted-level-1: #f6e4d2;
  --sklearn-color-unfitted-level-2: #ffe0b3;
  --sklearn-color-unfitted-level-3: chocolate;
  /* Definition of color scheme for fitted estimators */
  --sklearn-color-fitted-level-0: #f0f8ff;
  --sklearn-color-fitted-level-1: #d4ebff;
  --sklearn-color-fitted-level-2: #b3dbfd;
  --sklearn-color-fitted-level-3: cornflowerblue;
}

#sk-container-id-1.light {
  /* Specific color for light theme */
  --sklearn-color-text-on-default-background: black;
  --sklearn-color-background: white;
  --sklearn-color-border-box: black;
  --sklearn-color-icon: #696969;
}

#sk-container-id-1.dark {
  --sklearn-color-text-on-default-background: white;
  --sklearn-color-background: #111;
  --sklearn-color-border-box: white;
  --sklearn-color-icon: #878787;
}

#sk-container-id-1 {
  color: var(--sklearn-color-text);
}

#sk-container-id-1 pre {
  padding: 0;
}

#sk-container-id-1 input.sk-hidden--visually {
  border: 0;
  clip: rect(1px 1px 1px 1px);
  clip: rect(1px, 1px, 1px, 1px);
  height: 1px;
  margin: -1px;
  overflow: hidden;
  padding: 0;
  position: absolute;
  width: 1px;
}

#sk-container-id-1 div.sk-dashed-wrapped {
  border: 1px dashed var(--sklearn-color-line);
  margin: 0 0.4em 0.5em 0.4em;
  box-sizing: border-box;
  padding-bottom: 0.4em;
  background-color: var(--sklearn-color-background);
}

#sk-container-id-1 div.sk-container {
  /* jupyter's `normalize.less` sets `[hidden] { display: none; }`
     but bootstrap.min.css set `[hidden] { display: none !important; }`
     so we also need the `!important` here to be able to override the
     default hidden behavior on the sphinx rendered scikit-learn.org.
     See: https://github.com/scikit-learn/scikit-learn/issues/21755 */
  display: inline-block !important;
  position: relative;
}

#sk-container-id-1 div.sk-text-repr-fallback {
  display: none;
}

div.sk-parallel-item,
div.sk-serial,
div.sk-item {
  /* draw centered vertical line to link estimators */
  background-image: linear-gradient(var(--sklearn-color-text-on-default-background), var(--sklearn-color-text-on-default-background));
  background-size: 2px 100%;
  background-repeat: no-repeat;
  background-position: center center;
}

/* Parallel-specific style estimator block */

#sk-container-id-1 div.sk-parallel-item::after {
  content: "";
  width: 100%;
  border-bottom: 2px solid var(--sklearn-color-text-on-default-background);
  flex-grow: 1;
}

#sk-container-id-1 div.sk-parallel {
  display: flex;
  align-items: stretch;
  justify-content: center;
  background-color: var(--sklearn-color-background);
  position: relative;
}

#sk-container-id-1 div.sk-parallel-item {
  display: flex;
  flex-direction: column;
}

#sk-container-id-1 div.sk-parallel-item:first-child::after {
  align-self: flex-end;
  width: 50%;
}

#sk-container-id-1 div.sk-parallel-item:last-child::after {
  align-self: flex-start;
  width: 50%;
}

#sk-container-id-1 div.sk-parallel-item:only-child::after {
  width: 0;
}

/* Serial-specific style estimator block */

#sk-container-id-1 div.sk-serial {
  display: flex;
  flex-direction: column;
  align-items: center;
  background-color: var(--sklearn-color-background);
  padding-right: 1em;
  padding-left: 1em;
}


/* Toggleable style: style used for estimator/Pipeline/ColumnTransformer box that is
clickable and can be expanded/collapsed.
- Pipeline and ColumnTransformer use this feature and define the default style
- Estimators will overwrite some part of the style using the `sk-estimator` class
*/

/* Pipeline and ColumnTransformer style (default) */

#sk-container-id-1 div.sk-toggleable {
  /* Default theme specific background. It is overwritten whether we have a
  specific estimator or a Pipeline/ColumnTransformer */
  background-color: var(--sklearn-color-background);
}

/* Toggleable label */
#sk-container-id-1 label.sk-toggleable__label {
  cursor: pointer;
  display: flex;
  width: 100%;
  margin-bottom: 0;
  padding: 0.5em;
  box-sizing: border-box;
  text-align: center;
  align-items: center;
  justify-content: center;
  gap: 0.5em;
}

#sk-container-id-1 label.sk-toggleable__label .caption {
  font-size: 0.6rem;
  font-weight: lighter;
  color: var(--sklearn-color-text-muted);
}

#sk-container-id-1 label.sk-toggleable__label-arrow:before {
  /* Arrow on the left of the label */
  content: "▸";
  float: left;
  margin-right: 0.25em;
  color: var(--sklearn-color-icon);
}

#sk-container-id-1 label.sk-toggleable__label-arrow:hover:before {
  color: var(--sklearn-color-text);
}

/* Toggleable content - dropdown */

#sk-container-id-1 div.sk-toggleable__content {
  display: none;
  text-align: left;
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-0);
}

#sk-container-id-1 div.sk-toggleable__content.fitted {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-0);
}

#sk-container-id-1 div.sk-toggleable__content pre {
  margin: 0.2em;
  border-radius: 0.25em;
  color: var(--sklearn-color-text);
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-0);
}

#sk-container-id-1 div.sk-toggleable__content.fitted pre {
  /* unfitted */
  background-color: var(--sklearn-color-fitted-level-0);
}

#sk-container-id-1 input.sk-toggleable__control:checked~div.sk-toggleable__content {
  /* Expand drop-down */
  display: block;
  width: 100%;
  overflow: visible;
}

#sk-container-id-1 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {
  content: "▾";
}

/* Pipeline/ColumnTransformer-specific style */

#sk-container-id-1 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {
  color: var(--sklearn-color-text);
  background-color: var(--sklearn-color-unfitted-level-2);
}

#sk-container-id-1 div.sk-label.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {
  background-color: var(--sklearn-color-fitted-level-2);
}

/* Estimator-specific style */

/* Colorize estimator box */
#sk-container-id-1 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-2);
}

#sk-container-id-1 div.sk-estimator.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-2);
}

#sk-container-id-1 div.sk-label label.sk-toggleable__label,
#sk-container-id-1 div.sk-label label {
  /* The background is the default theme color */
  color: var(--sklearn-color-text-on-default-background);
}

/* On hover, darken the color of the background */
#sk-container-id-1 div.sk-label:hover label.sk-toggleable__label {
  color: var(--sklearn-color-text);
  background-color: var(--sklearn-color-unfitted-level-2);
}

/* Label box, darken color on hover, fitted */
#sk-container-id-1 div.sk-label.fitted:hover label.sk-toggleable__label.fitted {
  color: var(--sklearn-color-text);
  background-color: var(--sklearn-color-fitted-level-2);
}

/* Estimator label */

#sk-container-id-1 div.sk-label label {
  font-family: monospace;
  font-weight: bold;
  line-height: 1.2em;
}

#sk-container-id-1 div.sk-label-container {
  text-align: center;
}

/* Estimator-specific */
#sk-container-id-1 div.sk-estimator {
  font-family: monospace;
  border: 1px dotted var(--sklearn-color-border-box);
  border-radius: 0.25em;
  box-sizing: border-box;
  margin-bottom: 0.5em;
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-0);
}

#sk-container-id-1 div.sk-estimator.fitted {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-0);
}

/* on hover */
#sk-container-id-1 div.sk-estimator:hover {
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-2);
}

#sk-container-id-1 div.sk-estimator.fitted:hover {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-2);
}

/* Specification for estimator info (e.g. "i" and "?") */

/* Common style for "i" and "?" */

.sk-estimator-doc-link,
a:link.sk-estimator-doc-link,
a:visited.sk-estimator-doc-link {
  float: right;
  font-size: smaller;
  line-height: 1em;
  font-family: monospace;
  background-color: var(--sklearn-color-unfitted-level-0);
  border-radius: 1em;
  height: 1em;
  width: 1em;
  text-decoration: none !important;
  margin-left: 0.5em;
  text-align: center;
  /* unfitted */
  border: var(--sklearn-color-unfitted-level-3) 1pt solid;
  color: var(--sklearn-color-unfitted-level-3);
}

.sk-estimator-doc-link.fitted,
a:link.sk-estimator-doc-link.fitted,
a:visited.sk-estimator-doc-link.fitted {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-0);
  border: var(--sklearn-color-fitted-level-3) 1pt solid;
  color: var(--sklearn-color-fitted-level-3);
}

/* On hover */
div.sk-estimator:hover .sk-estimator-doc-link:hover,
.sk-estimator-doc-link:hover,
div.sk-label-container:hover .sk-estimator-doc-link:hover,
.sk-estimator-doc-link:hover {
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-3);
  border: var(--sklearn-color-fitted-level-0) 1pt solid;
  color: var(--sklearn-color-unfitted-level-0);
  text-decoration: none;
}

div.sk-estimator.fitted:hover .sk-estimator-doc-link.fitted:hover,
.sk-estimator-doc-link.fitted:hover,
div.sk-label-container:hover .sk-estimator-doc-link.fitted:hover,
.sk-estimator-doc-link.fitted:hover {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-3);
  border: var(--sklearn-color-fitted-level-0) 1pt solid;
  color: var(--sklearn-color-fitted-level-0);
  text-decoration: none;
}

/* Span, style for the box shown on hovering the info icon */
.sk-estimator-doc-link span {
  display: none;
  z-index: 9999;
  position: relative;
  font-weight: normal;
  right: .2ex;
  padding: .5ex;
  margin: .5ex;
  width: min-content;
  min-width: 20ex;
  max-width: 50ex;
  color: var(--sklearn-color-text);
  box-shadow: 2pt 2pt 4pt #999;
  /* unfitted */
  background: var(--sklearn-color-unfitted-level-0);
  border: .5pt solid var(--sklearn-color-unfitted-level-3);
}

.sk-estimator-doc-link.fitted span {
  /* fitted */
  background: var(--sklearn-color-fitted-level-0);
  border: var(--sklearn-color-fitted-level-3);
}

.sk-estimator-doc-link:hover span {
  display: block;
}

/* "?"-specific style due to the `<a>` HTML tag */

#sk-container-id-1 a.estimator_doc_link {
  float: right;
  font-size: 1rem;
  line-height: 1em;
  font-family: monospace;
  background-color: var(--sklearn-color-unfitted-level-0);
  border-radius: 1rem;
  height: 1rem;
  width: 1rem;
  text-decoration: none;
  /* unfitted */
  color: var(--sklearn-color-unfitted-level-1);
  border: var(--sklearn-color-unfitted-level-1) 1pt solid;
}

#sk-container-id-1 a.estimator_doc_link.fitted {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-0);
  border: var(--sklearn-color-fitted-level-1) 1pt solid;
  color: var(--sklearn-color-fitted-level-1);
}

/* On hover */
#sk-container-id-1 a.estimator_doc_link:hover {
  /* unfitted */
  background-color: var(--sklearn-color-unfitted-level-3);
  color: var(--sklearn-color-background);
  text-decoration: none;
}

#sk-container-id-1 a.estimator_doc_link.fitted:hover {
  /* fitted */
  background-color: var(--sklearn-color-fitted-level-3);
}

.estimator-table {
    font-family: monospace;
}

.estimator-table summary {
    padding: .5rem;
    cursor: pointer;
}

.estimator-table summary::marker {
    font-size: 0.7rem;
}

.estimator-table details[open] {
    padding-left: 0.1rem;
    padding-right: 0.1rem;
    padding-bottom: 0.3rem;
}

.estimator-table .parameters-table {
    margin-left: auto !important;
    margin-right: auto !important;
    margin-top: 0;
}

.estimator-table .parameters-table tr:nth-child(odd) {
    background-color: #fff;
}

.estimator-table .parameters-table tr:nth-child(even) {
    background-color: #f6f6f6;
}

.estimator-table .parameters-table tr:hover {
    background-color: #e0e0e0;
}

.estimator-table table td {
    border: 1px solid rgba(106, 105, 104, 0.232);
}

/*
    `table td`is set in notebook with right text-align.
    We need to overwrite it.
*/
.estimator-table table td.param {
    text-align: left;
    position: relative;
    padding: 0;
}

.user-set td {
    color:rgb(255, 94, 0);
    text-align: left !important;
}

.user-set td.value {
    color:rgb(255, 94, 0);
    background-color: transparent;
}

.default td {
    color: black;
    text-align: left !important;
}

.user-set td i,
.default td i {
    color: black;
}

/*
    Styles for parameter documentation links
    We need styling for visited so jupyter doesn't overwrite it
*/
a.param-doc-link,
a.param-doc-link:link,
a.param-doc-link:visited {
    text-decoration: underline dashed;
    text-underline-offset: .3em;
    color: inherit;
    display: block;
    padding: .5em;
}

/* "hack" to make the entire area of the cell containing the link clickable */
a.param-doc-link::before {
    position: absolute;
    content: "";
    inset: 0;
}

.param-doc-description {
    display: none;
    position: absolute;
    z-index: 9999;
    left: 0;
    padding: .5ex;
    margin-left: 1.5em;
    color: var(--sklearn-color-text);
    box-shadow: .3em .3em .4em #999;
    width: max-content;
    text-align: left;
    max-height: 10em;
    overflow-y: auto;

    /* unfitted */
    background: var(--sklearn-color-unfitted-level-0);
    border: thin solid var(--sklearn-color-unfitted-level-3);
}

/* Fitted state for parameter tooltips */
.fitted .param-doc-description {
    /* fitted */
    background: var(--sklearn-color-fitted-level-0);
    border: thin solid var(--sklearn-color-fitted-level-3);
}

.param-doc-link:hover .param-doc-description {
    display: block;
}

.copy-paste-icon {
    background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tIUZvbnQgQXdlc29tZSBGcmVlIDYuNy4yIGJ5IEBmb250YXdlc29tZSAtIGh0dHBzOi8vZm9udGF3ZXNvbWUuY29tIExpY2Vuc2UgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbS9saWNlbnNlL2ZyZWUgQ29weXJpZ2h0IDIwMjUgRm9udGljb25zLCBJbmMuLS0+PHBhdGggZD0iTTIwOCAwTDMzMi4xIDBjMTIuNyAwIDI0LjkgNS4xIDMzLjkgMTQuMWw2Ny45IDY3LjljOSA5IDE0LjEgMjEuMiAxNC4xIDMzLjlMNDQ4IDMzNmMwIDI2LjUtMjEuNSA0OC00OCA0OGwtMTkyIDBjLTI2LjUgMC00OC0yMS41LTQ4LTQ4bDAtMjg4YzAtMjYuNSAyMS41LTQ4IDQ4LTQ4ek00OCAxMjhsODAgMCAwIDY0LTY0IDAgMCAyNTYgMTkyIDAgMC0zMiA2NCAwIDAgNDhjMCAyNi41LTIxLjUgNDgtNDggNDhMNDggNTEyYy0yNi41IDAtNDgtMjEuNS00OC00OEwwIDE3NmMwLTI2LjUgMjEuNS00OCA0OC00OHoiLz48L3N2Zz4=);
    background-repeat: no-repeat;
    background-size: 14px 14px;
    background-position: 0;
    display: inline-block;
    width: 14px;
    height: 14px;
    cursor: pointer;
}
</style><div id="sk-container-id-1" class="sk-top-container"><div class="sk-text-repr-fallback"><pre>Pipeline(steps=[('standardscaler', StandardScaler()),
                ('kneighborsregressor', KNeighborsRegressor())])</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br>On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class="sk-container" hidden=""><div class="sk-item sk-dashed-wrapped"><div class="sk-label-container"><div class="sk-label  sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-1" type="checkbox"><label for="sk-estimator-id-1" class="sk-toggleable__label  sk-toggleable__label-arrow"><div><div>Pipeline</div></div><div><a class="sk-estimator-doc-link " rel="noreferrer" target="_blank" href="https://scikit-learn.org/1.8/modules/generated/sklearn.pipeline.Pipeline.html">?<span>Documentation for Pipeline</span></a><span class="sk-estimator-doc-link ">i<span>Not fitted</span></span></div></label><div class="sk-toggleable__content " data-param-prefix="">
        <div class="estimator-table">
            <details>
                <summary>Parameters</summary>
                
<table class="parameters-table caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<tbody>
<tr class="user-set odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.pipeline.Pipeline.html#:~:text=steps,-list%20of%20tuples" class="param-doc-link" rel="noreferrer" target="_blank">steps <span class="param-doc-description">steps: list of tuples<br>
<br>
List of (name of step, estimator) tuples that are to be chained in<br>
sequential order. To be compatible with the scikit-learn API, all steps<br>
must define `fit`. All non-last steps must also define `transform`. See<br>
:ref:`Combining Estimators <combining_estimators>` for more details.</combining_estimators></span></a></td>
<td class="value">[('standardscaler', ...), ('kneighborsregressor', ...)]</td>
</tr>
<tr class="default even">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.pipeline.Pipeline.html#:~:text=transform_input,-list%20of%20str%2C%20default%3DNone" class="param-doc-link" rel="noreferrer" target="_blank">transform_input <span class="param-doc-description">transform_input: list of str, default=None<br>
<br>
The names of the :term:`metadata` parameters that should be transformed by the<br>
pipeline before passing it to the step consuming it.<br>
<br>
This enables transforming some input arguments to ``fit`` (other than ``X``)<br>
to be transformed by the steps of the pipeline up to the step which requires<br>
them. Requirement is defined via :ref:`metadata routing <metadata_routing>`.<br>
For instance, this can be used to pass a validation set through the pipeline.<br>
<br>
You can only set this if metadata routing is enabled, which you<br>
can enable using ``sklearn.set_config(enable_metadata_routing=True)``.<br>
<br>
.. versionadded:: 1.6</metadata_routing></span></a></td>
<td class="value">None</td>
</tr>
<tr class="default odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.pipeline.Pipeline.html#:~:text=memory,-str%20or%20object%20with%20the%20joblib.Memory%20interface%2C%20default%3DNone" class="param-doc-link" rel="noreferrer" target="_blank">memory <span class="param-doc-description">memory: str or object with the joblib.Memory interface, default=None<br>
<br>
Used to cache the fitted transformers of the pipeline. The last step<br>
will never be cached, even if it is a transformer. By default, no<br>
caching is performed. If a string is given, it is the path to the<br>
caching directory. Enabling caching triggers a clone of the transformers<br>
before fitting. Therefore, the transformer instance given to the<br>
pipeline cannot be inspected directly. Use the attribute ``named_steps``<br>
or ``steps`` to inspect estimators within the pipeline. Caching the<br>
transformers is advantageous when fitting is time consuming. See<br>
:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`<br>
for an example on how to enable caching.</span></a></td>
<td class="value">None</td>
</tr>
<tr class="default even">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.pipeline.Pipeline.html#:~:text=verbose,-bool%2C%20default%3DFalse" class="param-doc-link" rel="noreferrer" target="_blank">verbose <span class="param-doc-description">verbose: bool, default=False<br>
<br>
If True, the time elapsed while fitting each step will be printed as it<br>
is completed.</span></a></td>
<td class="value">False</td>
</tr>
</tbody>
</table>

            </details>
        </div>
    </div></div></div><div class="sk-serial"><div class="sk-item"><div class="sk-estimator  sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-2" type="checkbox"><label for="sk-estimator-id-2" class="sk-toggleable__label  sk-toggleable__label-arrow"><div><div>StandardScaler</div></div><div><a class="sk-estimator-doc-link " rel="noreferrer" target="_blank" href="https://scikit-learn.org/1.8/modules/generated/sklearn.preprocessing.StandardScaler.html">?<span>Documentation for StandardScaler</span></a></div></label><div class="sk-toggleable__content " data-param-prefix="standardscaler__">
        <div class="estimator-table">
            <details>
                <summary>Parameters</summary>
                
<table class="parameters-table caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<tbody>
<tr class="default odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.preprocessing.StandardScaler.html#:~:text=copy,-bool%2C%20default%3DTrue" class="param-doc-link" rel="noreferrer" target="_blank">copy <span class="param-doc-description">copy: bool, default=True<br>
<br>
If False, try to avoid a copy and do inplace scaling instead.<br>
This is not guaranteed to always work inplace; e.g. if the data is<br>
not a NumPy array or scipy.sparse CSR matrix, a copy may still be<br>
returned.</span></a></td>
<td class="value">True</td>
</tr>
<tr class="default even">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.preprocessing.StandardScaler.html#:~:text=with_mean,-bool%2C%20default%3DTrue" class="param-doc-link" rel="noreferrer" target="_blank">with_mean <span class="param-doc-description">with_mean: bool, default=True<br>
<br>
If True, center the data before scaling.<br>
This does not work (and will raise an exception) when attempted on<br>
sparse matrices, because centering them entails building a dense<br>
matrix which in common use cases is likely to be too large to fit in<br>
memory.</span></a></td>
<td class="value">True</td>
</tr>
<tr class="default odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.preprocessing.StandardScaler.html#:~:text=with_std,-bool%2C%20default%3DTrue" class="param-doc-link" rel="noreferrer" target="_blank">with_std <span class="param-doc-description">with_std: bool, default=True<br>
<br>
If True, scale the data to unit variance (or equivalently,<br>
unit standard deviation).</span></a></td>
<td class="value">True</td>
</tr>
</tbody>
</table>

            </details>
        </div>
    </div></div></div><div class="sk-item"><div class="sk-estimator  sk-toggleable"><input class="sk-toggleable__control sk-hidden--visually" id="sk-estimator-id-3" type="checkbox"><label for="sk-estimator-id-3" class="sk-toggleable__label  sk-toggleable__label-arrow"><div><div>KNeighborsRegressor</div></div><div><a class="sk-estimator-doc-link " rel="noreferrer" target="_blank" href="https://scikit-learn.org/1.8/modules/generated/sklearn.neighbors.KNeighborsRegressor.html">?<span>Documentation for KNeighborsRegressor</span></a></div></label><div class="sk-toggleable__content " data-param-prefix="kneighborsregressor__">
        <div class="estimator-table">
            <details>
                <summary>Parameters</summary>
                
<table class="parameters-table caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<tbody>
<tr class="default odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.neighbors.KNeighborsRegressor.html#:~:text=n_neighbors,-int%2C%20default%3D5" class="param-doc-link" rel="noreferrer" target="_blank">n_neighbors <span class="param-doc-description">n_neighbors: int, default=5<br>
<br>
Number of neighbors to use by default for :meth:`kneighbors` queries.</span></a></td>
<td class="value">5</td>
</tr>
<tr class="default even">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.neighbors.KNeighborsRegressor.html#:~:text=weights,-%7B%27uniform%27%2C%20%27distance%27%7D%2C%20callable%20or%20None%2C%20default%3D%27uniform%27" class="param-doc-link" rel="noreferrer" target="_blank">weights <span class="param-doc-description">weights: {'uniform', 'distance'}, callable or None, default='uniform'<br>
<br>
Weight function used in prediction. Possible values:<br>
<br>
- 'uniform' : uniform weights. All points in each neighborhood<br>
are weighted equally.<br>
- 'distance' : weight points by the inverse of their distance.<br>
in this case, closer neighbors of a query point will have a<br>
greater influence than neighbors which are further away.<br>
- [callable] : a user-defined function which accepts an<br>
array of distances, and returns an array of the same shape<br>
containing the weights.<br>
<br>
Uniform weights are used by default.<br>
<br>
See the following example for a demonstration of the impact of<br>
different weighting schemes on predictions:<br>
:ref:`sphx_glr_auto_examples_neighbors_plot_regression.py`.</span></a></td>
<td class="value">'uniform'</td>
</tr>
<tr class="default odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.neighbors.KNeighborsRegressor.html#:~:text=algorithm,-%7B%27auto%27%2C%20%27ball_tree%27%2C%20%27kd_tree%27%2C%20%27brute%27%7D%2C%20default%3D%27auto%27" class="param-doc-link" rel="noreferrer" target="_blank">algorithm <span class="param-doc-description">algorithm: {'auto', 'ball_tree', 'kd_tree', 'brute'}, default='auto'<br>
<br>
Algorithm used to compute the nearest neighbors:<br>
<br>
- 'ball_tree' will use :class:`BallTree`<br>
- 'kd_tree' will use :class:`KDTree`<br>
- 'brute' will use a brute-force search.<br>
- 'auto' will attempt to decide the most appropriate algorithm<br>
based on the values passed to :meth:`fit` method.<br>
<br>
Note: fitting on sparse input will override the setting of<br>
this parameter, using brute force.</span></a></td>
<td class="value">'auto'</td>
</tr>
<tr class="default even">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.neighbors.KNeighborsRegressor.html#:~:text=leaf_size,-int%2C%20default%3D30" class="param-doc-link" rel="noreferrer" target="_blank">leaf_size <span class="param-doc-description">leaf_size: int, default=30<br>
<br>
Leaf size passed to BallTree or KDTree. This can affect the<br>
speed of the construction and query, as well as the memory<br>
required to store the tree. The optimal value depends on the<br>
nature of the problem.</span></a></td>
<td class="value">30</td>
</tr>
<tr class="default odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.neighbors.KNeighborsRegressor.html#:~:text=p,-float%2C%20default%3D2" class="param-doc-link" rel="noreferrer" target="_blank">p <span class="param-doc-description">p: float, default=2<br>
<br>
Power parameter for the Minkowski metric. When p = 1, this is<br>
equivalent to using manhattan_distance (l1), and euclidean_distance<br>
(l2) for p = 2. For arbitrary p, minkowski_distance (l_p) is used.</span></a></td>
<td class="value">2</td>
</tr>
<tr class="default even">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.neighbors.KNeighborsRegressor.html#:~:text=metric,-str%2C%20DistanceMetric%20object%20or%20callable%2C%20default%3D%27minkowski%27" class="param-doc-link" rel="noreferrer" target="_blank">metric <span class="param-doc-description">metric: str, DistanceMetric object or callable, default='minkowski'<br>
<br>
Metric to use for distance computation. Default is "minkowski", which<br>
results in the standard Euclidean distance when p = 2. See the<br>
documentation of `scipy.spatial.distance<br>
&lt; docs.scipy.org doc scipy reference spatial.distance.html&gt;`_ and<br>
the metrics listed in<br>
:class:`~sklearn.metrics.pairwise.distance_metrics` for valid metric<br>
values.<br>
<br>
If metric is "precomputed", X is assumed to be a distance matrix and<br>
must be square during fit. X may be a :term:`sparse graph`, in which<br>
case only "nonzero" elements may be considered neighbors.<br>
<br>
If metric is a callable function, it takes two arrays representing 1D<br>
vectors as inputs and must return one value indicating the distance<br>
between those vectors. This works for Scipy's metrics, but is less<br>
efficient than passing the metric name as a string.<br>
<br>
If metric is a DistanceMetric object, it will be passed directly to<br>
the underlying computation routines.</span></a></td>
<td class="value">'minkowski'</td>
</tr>
<tr class="default odd">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.neighbors.KNeighborsRegressor.html#:~:text=metric_params,-dict%2C%20default%3DNone" class="param-doc-link" rel="noreferrer" target="_blank">metric_params <span class="param-doc-description">metric_params: dict, default=None<br>
<br>
Additional keyword arguments for the metric function.</span></a></td>
<td class="value">None</td>
</tr>
<tr class="default even">
<td><em></em></td>
<td class="param"><a href="https://scikit-learn.org/1.8/modules/generated/sklearn.neighbors.KNeighborsRegressor.html#:~:text=n_jobs,-int%2C%20default%3DNone" class="param-doc-link" rel="noreferrer" target="_blank">n_jobs <span class="param-doc-description">n_jobs: int, default=None<br>
<br>
The number of parallel jobs to run for neighbors search.<br>
``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.<br>
``-1`` means using all processors. See :term:`Glossary <n_jobs>`<br>
for more details.<br>
Doesn't affect :meth:`fit` method.</n_jobs></span></a></td>
<td class="value">None</td>
</tr>
</tbody>
</table>

            </details>
        </div>
    </div></div></div></div></div></div></div><script>function copyToClipboard(text, element) {
    // Get the parameter prefix from the closest toggleable content
    const toggleableContent = element.closest('.sk-toggleable__content');
    const paramPrefix = toggleableContent ? toggleableContent.dataset.paramPrefix : '';
    const fullParamName = paramPrefix ? `${paramPrefix}${text}` : text;

    const originalStyle = element.style;
    const computedStyle = window.getComputedStyle(element);
    const originalWidth = computedStyle.width;
    const originalHTML = element.innerHTML.replace('Copied!', '');

    navigator.clipboard.writeText(fullParamName)
        .then(() => {
            element.style.width = originalWidth;
            element.style.color = 'green';
            element.innerHTML = "Copied!";

            setTimeout(() => {
                element.innerHTML = originalHTML;
                element.style = originalStyle;
            }, 2000);
        })
        .catch(err => {
            console.error('Failed to copy:', err);
            element.style.color = 'red';
            element.innerHTML = "Failed!";
            setTimeout(() => {
                element.innerHTML = originalHTML;
                element.style = originalStyle;
            }, 2000);
        });
    return false;
}

document.querySelectorAll('.copy-paste-icon').forEach(function(element) {
    const toggleableContent = element.closest('.sk-toggleable__content');
    const paramPrefix = toggleableContent ? toggleableContent.dataset.paramPrefix : '';
    const paramName = element.parentElement.nextElementSibling
        .textContent.trim().split(' ')[0];
    const fullParamName = paramPrefix ? `${paramPrefix}${paramName}` : paramName;

    element.setAttribute('title', fullParamName);
});


/**
 * Adapted from Skrub
 * https://github.com/skrub-data/skrub/blob/403466d1d5d4dc76a7ef569b3f8228db59a31dc3/skrub/_reporting/_data/templates/report.js#L789
 * @returns "light" or "dark"
 */
function detectTheme(element) {
    const body = document.querySelector('body');

    // Check VSCode theme
    const themeKindAttr = body.getAttribute('data-vscode-theme-kind');
    const themeNameAttr = body.getAttribute('data-vscode-theme-name');

    if (themeKindAttr && themeNameAttr) {
        const themeKind = themeKindAttr.toLowerCase();
        const themeName = themeNameAttr.toLowerCase();

        if (themeKind.includes("dark") || themeName.includes("dark")) {
            return "dark";
        }
        if (themeKind.includes("light") || themeName.includes("light")) {
            return "light";
        }
    }

    // Check Jupyter theme
    if (body.getAttribute('data-jp-theme-light') === 'false') {
        return 'dark';
    } else if (body.getAttribute('data-jp-theme-light') === 'true') {
        return 'light';
    }

    // Guess based on a parent element's color
    const color = window.getComputedStyle(element.parentNode, null).getPropertyValue('color');
    const match = color.match(/^rgb\s*\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)\s*$/i);
    if (match) {
        const [r, g, b] = [
            parseFloat(match[1]),
            parseFloat(match[2]),
            parseFloat(match[3])
        ];

        // https://en.wikipedia.org/wiki/HSL_and_HSV#Lightness
        const luma = 0.299 * r + 0.587 * g + 0.114 * b;

        if (luma > 180) {
            // If the text is very bright we have a dark theme
            return 'dark';
        }
        if (luma < 75) {
            // If the text is very dark we have a light theme
            return 'light';
        }
        // Otherwise fall back to the next heuristic.
    }

    // Fallback to system preference
    return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
}


function forceTheme(elementId) {
    const estimatorElement = document.querySelector(`#${elementId}`);
    if (estimatorElement === null) {
        console.error(`Element with id ${elementId} not found.`);
    } else {
        const theme = detectTheme(estimatorElement);
        estimatorElement.classList.add(theme);
    }
}

forceTheme('sk-container-id-1');</script>
</div>
</div>
</section>
<section id="grid-search-for-best-k-with-cross-validation" class="level4">
<h4 class="anchored" data-anchor-id="grid-search-for-best-k-with-cross-validation">Grid Search for best K with Cross Validation</h4>
<p>We will perform a grid seearch to identify the optimal number of neighbours (K) for the K-Nearest Neighbors regression model. This involves evaluating a range of K values between 1 and 29 using cross validation on the training set to measure model performance. The best performing value of K will be used to fit the final model and evaluate its performance on the test set,</p>
<div id="0c5863c4" class="cell" data-execution_count="12">
<div class="cell-output cell-output-stdout">
<pre><code>Best Model: Pipeline(steps=[('standardscaler', StandardScaler()),
                ('kneighborsregressor', KNeighborsRegressor(n_neighbors=21))])

Best K: 21
Best CV Score: 0.34352
Best Train Score: 0.41222</code></pre>
</div>
</div>
<div id="e1658896" class="cell" data-execution_count="13">
<div class="cell-output cell-output-stdout">
<pre><code>Table 2: Results of Grid Search Cross Validation</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="13">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">params</th>
<th data-quarto-table-cell-role="th">mean_test_score</th>
<th data-quarto-table-cell-role="th">std_test_score</th>
<th data-quarto-table-cell-role="th">mean_train_score</th>
<th data-quarto-table-cell-role="th">std_train_score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>{'kneighborsregressor__n_neighbors': 1}</td>
<td>0.092826</td>
<td>0.069927</td>
<td>1.000000</td>
<td>0.000000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>{'kneighborsregressor__n_neighbors': 2}</td>
<td>0.230754</td>
<td>0.038078</td>
<td>0.779557</td>
<td>0.003860</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>{'kneighborsregressor__n_neighbors': 3}</td>
<td>0.286078</td>
<td>0.026086</td>
<td>0.668196</td>
<td>0.002550</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>{'kneighborsregressor__n_neighbors': 4}</td>
<td>0.319000</td>
<td>0.023478</td>
<td>0.605030</td>
<td>0.005425</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>{'kneighborsregressor__n_neighbors': 5}</td>
<td>0.330007</td>
<td>0.021589</td>
<td>0.564269</td>
<td>0.006124</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>{'kneighborsregressor__n_neighbors': 6}</td>
<td>0.334799</td>
<td>0.027805</td>
<td>0.536615</td>
<td>0.004802</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>{'kneighborsregressor__n_neighbors': 7}</td>
<td>0.335600</td>
<td>0.031329</td>
<td>0.515438</td>
<td>0.003305</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>{'kneighborsregressor__n_neighbors': 8}</td>
<td>0.339080</td>
<td>0.034541</td>
<td>0.498159</td>
<td>0.005880</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>{'kneighborsregressor__n_neighbors': 9}</td>
<td>0.339135</td>
<td>0.036526</td>
<td>0.481017</td>
<td>0.007277</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>{'kneighborsregressor__n_neighbors': 10}</td>
<td>0.339148</td>
<td>0.034313</td>
<td>0.469061</td>
<td>0.007079</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>{'kneighborsregressor__n_neighbors': 11}</td>
<td>0.341202</td>
<td>0.032866</td>
<td>0.457831</td>
<td>0.006933</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>{'kneighborsregressor__n_neighbors': 12}</td>
<td>0.342900</td>
<td>0.033049</td>
<td>0.448369</td>
<td>0.007094</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>{'kneighborsregressor__n_neighbors': 13}</td>
<td>0.340503</td>
<td>0.032321</td>
<td>0.440760</td>
<td>0.005998</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>{'kneighborsregressor__n_neighbors': 14}</td>
<td>0.342719</td>
<td>0.032349</td>
<td>0.434649</td>
<td>0.006146</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>{'kneighborsregressor__n_neighbors': 15}</td>
<td>0.342510</td>
<td>0.033861</td>
<td>0.428574</td>
<td>0.007233</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">15</th>
<td>{'kneighborsregressor__n_neighbors': 16}</td>
<td>0.340572</td>
<td>0.034144</td>
<td>0.423658</td>
<td>0.007189</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">16</th>
<td>{'kneighborsregressor__n_neighbors': 17}</td>
<td>0.341174</td>
<td>0.031943</td>
<td>0.419360</td>
<td>0.007718</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">17</th>
<td>{'kneighborsregressor__n_neighbors': 18}</td>
<td>0.342285</td>
<td>0.029977</td>
<td>0.415777</td>
<td>0.007309</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">18</th>
<td>{'kneighborsregressor__n_neighbors': 19}</td>
<td>0.343315</td>
<td>0.027831</td>
<td>0.412036</td>
<td>0.007819</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">19</th>
<td>{'kneighborsregressor__n_neighbors': 20}</td>
<td>0.341989</td>
<td>0.025687</td>
<td>0.409032</td>
<td>0.007432</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">20</th>
<td>{'kneighborsregressor__n_neighbors': 21}</td>
<td>0.343521</td>
<td>0.023684</td>
<td>0.406140</td>
<td>0.007375</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">21</th>
<td>{'kneighborsregressor__n_neighbors': 22}</td>
<td>0.342767</td>
<td>0.022638</td>
<td>0.403150</td>
<td>0.007853</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">22</th>
<td>{'kneighborsregressor__n_neighbors': 23}</td>
<td>0.340639</td>
<td>0.021639</td>
<td>0.399454</td>
<td>0.007989</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">23</th>
<td>{'kneighborsregressor__n_neighbors': 24}</td>
<td>0.339971</td>
<td>0.020606</td>
<td>0.396652</td>
<td>0.006926</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">24</th>
<td>{'kneighborsregressor__n_neighbors': 25}</td>
<td>0.340255</td>
<td>0.018380</td>
<td>0.393898</td>
<td>0.006990</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">25</th>
<td>{'kneighborsregressor__n_neighbors': 26}</td>
<td>0.341216</td>
<td>0.017916</td>
<td>0.391189</td>
<td>0.006672</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">26</th>
<td>{'kneighborsregressor__n_neighbors': 27}</td>
<td>0.340690</td>
<td>0.017444</td>
<td>0.389025</td>
<td>0.006448</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">27</th>
<td>{'kneighborsregressor__n_neighbors': 28}</td>
<td>0.340953</td>
<td>0.017448</td>
<td>0.387520</td>
<td>0.006708</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">28</th>
<td>{'kneighborsregressor__n_neighbors': 29}</td>
<td>0.341590</td>
<td>0.016661</td>
<td>0.385115</td>
<td>0.006346</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="6acc59ac" class="cell" data-execution_count="14">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="wine_quality_prediction_files/figure-html/cell-15-output-1.png" width="821" height="449" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="920234ec" class="cell" data-execution_count="15">
<div class="cell-output cell-output-stdout">
<pre><code>Best Model: Pipeline(steps=[('standardscaler', StandardScaler()),
                ('kneighborsregressor', KNeighborsRegressor(n_neighbors=21))])

Best K: 21
Best CV Score: 0.34352
Best Train Score: 0.41222</code></pre>
</div>
</div>
<p>The best value of K is 21, providing a CV score of 0.343 and training score of 0.412.</p>
</section>
<section id="evaluating-on-the-test-set" class="level4">
<h4 class="anchored" data-anchor-id="evaluating-on-the-test-set">Evaluating on the Test Set</h4>
<p>After selecting the optimal value of K = 21, we will fit the final K-Nearest Neighbors model on the training set and evaluate the model performance on unseen data (test set). We will use R^2 to assess the quality of the predictions.</p>
<div id="7bf01e09" class="cell" data-execution_count="16">
<div class="cell-output cell-output-stdout">
<pre><code>Test R^2 Score: 0.34658</code></pre>
</div>
</div>
<div id="40131dee" class="cell" data-execution_count="17">
<div class="cell-output cell-output-stdout">
<pre><code>Mean CV R^2 Score: 0.34352
Train R^2 Score: 0.41222
Test R^2 Score: 0.34658</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<p><strong>Summary of Findings</strong></p>
<p>In this project, we aimed to predict the sensory quality of “Vinho Verde” wine based on 11 physicochemical properties using a K-Nearest Neighbors (KNN) regression model. After standardizing the features and performing a grid search with cross-validation, we identified the optimal number of neighbors to be <span class="math inline">\(K = 21\)</span>. Evaluating this tuned model on our unseen test set yielded an <span class="math inline">\(R^2\)</span> score of 0.34658. This indicates that our model explains approximately 34.7% of the variance in wine quality scores.</p>
<p><strong>Were the Results Expected?</strong></p>
<p>While an <span class="math inline">\(R^2\)</span> score of 0.347 demonstrates a positive, measurable relationship between the chemical properties and quality, it highlights a relatively modest predictive performance. These results are not entirely surprising. As indicated by our exploratory data analysis, most physicochemical features had weak linear correlations with the quality score, with alcohol content (+0.44) and volatile acidity (-0.27) being the strongest predictors. Furthermore, wine tasting is an inherently subjective and highly complex sensory experience. A human’s perception of “quality” is influenced by intricate chemical interactions, aromatic compounds, and balance, which may not be fully captured by 11 basic chemical measurements or a simple distance-based algorithm like KNN.</p>
<p><strong>Impact of Findings</strong></p>
<p>Despite the modest accuracy, establishing this baseline relationship holds practical value for the wine industry. For wine producers and vineyards, predictive modeling can serve as an objective, early-stage screening tool. While it cannot entirely replace expert sommeliers or sensory panels, a chemical-based predictive model could be used during the fermentation and blending processes to flag potentially low-quality batches early on, saving time and resources in quality control. For consumers, quantifying these metrics paves the way for a more consistent product on store shelves.</p>
<p><strong>Future Questions and Next Steps</strong></p>
<p>The limitations of this study open the door to several promising avenues for future research:</p>
<ul>
<li><strong>Model Complexity:</strong> KNN treats all standardized features with equal weight when calculating distances. Future projects should explore more complex, tree-based models (such as Random Forests or Gradient Boosting) that can better capture non-linear relationships and interactions between complex chemical compounds.</li>
<li><strong>Feature Importance:</strong> Exploring algorithms that provide feature importance scores could help winemakers pinpoint exactly which chemical balances (e.g., the ratio of residual sugar to acidity) have the greatest impact on human taste.</li>
<li><strong>Dataset Segmentation:</strong> Red and white wines have fundamentally different chemical profiles and sensory expectations. A logical next step would be to separate the dataset and train distinct models for red and white wines to see if predictive accuracy improves when the wine types are isolated.</li>
</ul>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>Cortez, P., Cerdeira, A., Almeida, F., Matos, T., &amp; Reis, J. (2009). Modeling wine preferences by data mining from physicochemical properties. <em>Decision Support Systems</em>, <em>47</em>(4), 547–553. https://doi.org/10.1016/j.dss.2009.05.016</p>
<p>Dua, D., &amp; Graff, C. (2019). <em>UCI Machine Learning Repository</em>. University of California, Irvine, School of Information and Computer Sciences. https://archive.ics.uci.edu/ml</p>
<p>Hastie, T., Tibshirani, R., &amp; Friedman, J. (2009). <em>The elements of statistical learning: Data mining, inference, and prediction</em> (2nd ed.). Springer. https://doi.org/10.1007/978-0-387-84858-7</p>
<p>Pedregosa, F., Varoquaux, G., Gramfort, A., Michel, V., Thirion, B., Grisel, O., Blondel, M., Prettenhofer, P., Weiss, R., Dubourg, V., Vanderplas, J., Passos, A., Cournapeau, D., Brucher, M., Perrot, M., &amp; Duchesnay, É. (2011). Scikit-learn: Machine learning in Python. <em>Journal of Machine Learning Research</em>, <em>12</em>, 2825–2830.</p>

</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-CORTEZ2009547" class="csl-entry" role="listitem">
Cortez, Paulo, António Cerdeira, Fernando Almeida, Telmo Matos, and José Reis. 2009. <span>“Modeling Wine Preferences by Data Mining from Physicochemical Properties.”</span> <em>Decision Support Systems</em> 47 (4): 547–53. https://doi.org/<a href="https://doi.org/10.1016/j.dss.2009.05.016">https://doi.org/10.1016/j.dss.2009.05.016</a>.
</div>
<div id="ref-hastie_tibshirani_friedman_2009" class="csl-entry" role="listitem">
Hastie, Trevor, Robert Tibshirani, and Jerome Friedman. 2009. <em>The Elements of Statistical Learning, Second Edition : Data Mining, Inference, and Prediction</em>. 2nd ed. New York: Springer.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>